### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by mdowns56** [antoinebidault/DonutOutputCachingCore#3]
I'm currently working on a .NET framework project that uses another Donut caching solution. Unfortunately, it relies heavily on Html.Action, which won't work when we move to Core. I imagine you ran into a similar situation and created this project.

Do you have any plans on creating a nuget package for people to use?

Do you have any plans on supporting this project?

**Comment by antoinebidault** [comment]
At the moment, i know this nuget is used on 2 high traffic production websites in my last job. I have built it for replacing the old .net 4 DonutOutputCacheMvc. Now that I moved to a SPA stack, I wouldn't guarantee that i will actively maintain it... But I am open to any code contributions.

**Comment by antoinebidault** [comment]
I've seen the nuget is not more available and marked as obsolete. This is an issue with my nuget account. I'll fix it soon

**Comment by antoinebidault** [comment]
Ok, the package is not marked as obsolete anymore.
Then I've upgraded the package to version 1.0.40 with .Net 5.0 supports.
